### ISSUE TITLE
Sampler.sampleBuffer fails with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by DisPony** [mipt-npm/kmath#87]
kmath version = 0.1.4-dev-1
kotlin version 1.3.71
I got an exception when running this code:
```kotlin
fun main() {
    val sampler: Sampler<Double> = BasicSampler { it.chain { nextDouble() } }
    val data = sampler.sampleBuffer(RandomGenerator.default, 100)
    runBlocking {
        println(data.next())
    }
}
```
```
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:426)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$2$1.invoke(Distribution.kt:64)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$2$1.invoke(Distribution.kt)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$3.invoke(Distribution.kt:73)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$3.invoke(Distribution.kt)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$2.invokeSuspend(Distribution.kt:64)
	at scientifik.kmath.prob.DistributionKt$sampleBuffer$2.invoke(Distribution.kt)
	at scientifik.kmath.chains.ChainKt$collect$1.next(Chain.kt:134)
	at TestKt$main$1.invokeSuspend(test.kt:21)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at TestKt.main(test.kt:20)
	at TestKt.main(test.kt)

Process finished with exit code 1
```

It seems that problem in this line [link to method](https://github.com/mipt-npm/kmath/blob/ab7887a13c9d5cab94ee8f5659ed4edaa82db541/kmath-prob/src/commonMain/kotlin/scientifik/kmath/prob/Distribution.kt#L59):
`
val tmp = ArrayList<T>(size)
`
Because with following list allocation method returns expected result, at least in case above
```kotlin
fun <T : Any> Sampler<T>.sampleBuffer1(
    generator: RandomGenerator,
    size: Int,
    bufferFactory: BufferFactory<T> = Buffer.Companion::boxing
): Chain<Buffer<T>> {
    require(size > 1)
    //creating temporary storage once
    val tmp = MutableList<T?>(size) { null }

    return sample(generator).collect { chain ->
        for (i in tmp.indices) {
            tmp[i] = chain.next()
        }
        bufferFactory(size) { tmp[it]!! }
    }
}
```

**Comment by altavir** [comment]
Nice error report, thanks. I will look into it.
